name: Hit Miqaat API Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:      # manual trigger from GitHub UI

jobs:
  hit-api:
    runs-on: ubuntu-latest

    steps:
      - name: Hit Miqaat API
        env:
          API_URL: https://mqt-allocation.its52.com/api/v1/allocations/city-allocation/submit
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          curl -X POST "$API_URL" \
            -H "Authorization: Bearer $API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "concernGiven": false,
              "concernRequired": false,
              "choices": [{"itsId": 50435909,"cityId": 1}],
              "groupId": 50435909,
              "eventId": 4,
              "acceptedHold": true
            }'
